# Generated by Django 4.2.11 on 2026-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('patient_code', models.CharField(blank=True, default='', max_length=20)),
                ('accel_x', models.FloatField(default=0)),
                ('accel_y', models.FloatField(default=0)),
                ('accel_z', models.FloatField(default=9.81)),
                ('gyro_x', models.FloatField(default=0)),
                ('gyro_y', models.FloatField(default=0)),
                ('gyro_z', models.FloatField(default=0)),
                ('total_acceleration', models.FloatField(default=1.0)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
