# Generated by Django 4.2.11 on 2026-07-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_livesensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesensorreading',
            name='fall_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=20)),
                ('device_id', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('esp32', 'ESP32'), ('simulated', 'Simulation')], default='esp32', max_length=20)),
                ('acknowledged', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['patient_code', '-detected_at'], name='sensors_fal_patient_54ba93_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='ESP32-001', max_length=100)),
                ('patient_code', models.CharField(default='P001', max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('fall_detected', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['patient_code', '-received_at'], name='sensors_dev_patient_dbc643_idx'), models.Index(fields=['device_id', '-received_at'], name='sensors_dev_device__ddc384_idx')],
            },
        ),
    ]
