# Generated by Django 4.2.11 on 2026-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_monitoringcontext_patientlivestate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlivestate',
            name='fall_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientlivestate',
            name='gyro_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientlivestate',
            name='gyro_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientlivestate',
            name='gyro_z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
