# Generated by Django 4.2.11 on 2026-07-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_fall_risk_mpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='notif_type',
            field=models.CharField(choices=[('fall', 'Chute'), ('message', 'Message envoyé'), ('call', 'Appel'), ('email', 'E-mail'), ('gps', 'GPS')], default='fall', max_length=20),
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=20)),
                ('recipient_type', models.CharField(default='famille', max_length=20)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('geo_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fall_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='sensors.fallevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
