# Generated by Django 4.2.11 on 2026-05-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('features_used', models.JSONField(default=list)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='FragilityPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('features_used', models.JSONField(default=list)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fragility Prediction Models',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='training_data/')),
                ('samples_count', models.IntegerField()),
                ('data_source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Training Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_risk_score', models.FloatField()),
                ('fragility_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('confidence', models.FloatField()),
                ('fall_model_version', models.CharField(max_length=50)),
                ('fragility_model_version', models.CharField(max_length=50)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='patients.patient')),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['patient', '-predicted_at'], name='ml_models_p_patient_75a4f0_idx')],
            },
        ),
    ]
